const message = {
    ERROR_MESSAGE: "Unexpected error occurred, please try again!",
    TMS_CATEGORY_ALREDY_EXIST: "TMS category data already exist!",
    TMS_CATEGORY_ADDED: "TMS category data added successfully!",
    TMS_CATEGORY_DETAILS: "TMS category data details!",
    DATA_NOT_FOUND: "Data not found!",
    TMS_CATEGORY_UPDATED: "TMS category data update successfully!",
    TMS_CATEGORY_LOGGED_USER_REQUEST: "TMS Category logged in user Request Not Found!",
    TMS_CATEGORY_LOGGED_USER: "TMS category logged in user list Successfully!",
    TMS_CATEGORY_DELETED: "TMS category data deleted successfully!",
    TMS_STATUS_CATEGORY_ALREDY_EXIST: "TMS status category data already exist!",
    TMS_STATUS_CATEGORY_ADDED: "TMS status data added successfully!",
    TMS_STATUS_CATEGORY_DETAILS: "TMS status data details!",
    TMS_STATUS_CATEGORY_UPDATED: "TMS status data update successfully!",
    TMS_STATUS_CATEGORY_LOGGED_USER_REQUEST: "TMS status logged in user request not found!",
    TMS_STATUS_CATEGORY_LOGGED_USER: "TMS status list logged in user Successfully!",
    TMS_STATUS_CATEGORY_REQUEST_LIST: "TMS status request not found!",
    TMS_STATUS_CATEGORY_LIST: "TMS status list Successfully!",
    TMS_STATUS_CATEGORY_DELETED: "TMS status data deleted successfully!",
    TMS_SUB_CATEGORY_ALREDY_EXIST: "TMS sub-category data already exist!",
    TMS_SUB_CATEGORY_ADDED: "TMS sub-category data added successfully!",
    TMS_SUB_CATEGORY_DETAILS: "TMS sub-category data details!",
    TMS_SUB_CATEGORY_UPDATED: "TMS sub-category data update successfully!",
    TMS_SUB_CATEGORY_LOGGED_USER_REQUEST: "TMS sub-category logged in user request not found!",
    TMS_SUB_CATEGORY_LOGGED_USER: "TMS sub-category list logged in user Successfully",
    TMS_SUB_CATEGORY_REQUEST_LIST: "TMS sub-category request not found!",
    TMS_SUB_CATEGORY_LIST: "TMS sub-category list Successfully!",
    TMS_SUB_CATEGORY_DELETED: "TMS sub-category data deleted successfully!",
    TMS_SUB_STATUS_ALREDY_EXIST: "TMS sub-status data already exist!",
    TMS_SUB_STATUS_ADDED: "TMS sub-status data added successfully!",
    TMS_SUB_STATUS_DETAILS: "TMS sub-status data details!",
    TMS_SUB_STATUS_UPDATED: "TMS sub-status data update successfully!",
    TMS_SUB_STATUS_LOGGED_USER_REQUEST: "TMS sub-status logged in user request not found!",
    TMS_SUB_STATUS_LOGGED_USER: "TMS sub-status list logged in user Successfully!",
    TMS_SUB_STATUS_REQUEST_LIST: "TMS sub-status request not found!",
    TMS_SUB_STATUS_LIST: "TMS sub-status list Successfully!",
    TMS_SUB_STATUS_DELETED: "TMS sub-status data deleted successfully!",
}
module.exports = {
    message
};
